project:
  type: website
  output-dir: docs

website:
  title: "Heather Childers"
  favicon: images/logo.png
  navbar:
    title: false
    logo: images/logo.png
    logo-alt: "A pastel-colored illustration depicting a thriving community garden, showcasing innovative agricultural, climate engineering, and data analysis techniques.  The artwork includes floral elements, reflecting scientific principles in a creative and accessible way. The style blends scientific illustration with artistic expression, emphasizing community building through sustainable practices."
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: blogs.qmd
        text: Projects
      - href: xtra.qmd
        text: Leadership
      - href: cv/Childers_CV.pdf
        text: CV
#      - href: PasProj.qmd
#        text: Passions

        
    right:
      - href: https://github.com/hmchilders
        text: "<i class='bi bi-github' style='font-size: 3rem;'></i>"
  page-footer: 
    background: light
    left: "Heather Childers"
    right: 
      - icon: github
        href: https://github.com/hmchilders

format:
  html:
    theme: 
      - styles.scss
    mainfont: Playfair Display
    toc: true
    page-layout: full

editor: visual

