{
  "hash": "01091629a7d6e86a6d1246b514b063d4",
  "result": {
    "markdown": "---\ntitle: \"Investigate the Legacy of Redlining in Current Environmental (In)justice\" \ndescription: \"Geospatial Analysis & Remote Sensing Course Project\"\nfreeze: auto\nauthor: \n  - name: Heather Childers\n    url: hmchilders.github.io/\n    affiliation: Master of Environmental Data Science Program\n    affiliation-url: https://bren.ucsb.edu/masters-programs/master-environmental-data-science\n    #orcid: \ndate: 12-10-2023\ncategories: [MEDS, R, Geospatial, Environmental Justice]\nimage: Graph.png\ncitation: \n  url: hmchilders.github.io/Geospatial_Blogs/2023-11-10\n---\n\n\n\n\n# Investigate the Legacy of Redlining in Current Environmental (In)justice\n\n## Project Overview\n\nPresent-day environmental justice may reflect legacies of injustice in the past. The United States has a long history of racial segregation which is still visible. During the 1930's the Home Owners' Loan Corporation (HOLC), as part of the New Deal, rated neighborhoods based on their perceived safety for real estate investment. Their ranking system, (A (green), B (blue), C (yellow), D (red)) was then used to block access to loans for home ownership. Colloquially known as \"redlining\", this practice has had widely-documented consequences not only for community wealth, but also health.^[1](https://eds-223-geospatial.github.io/assignments/HW2.html#fn1)^ Redlined neighborhoods have less greenery^[2](https://eds-223-geospatial.github.io/assignments/HW2.html#fn2)^ and are hotter than other neighborhoods.^[3](https://eds-223-geospatial.github.io/assignments/HW2.html#fn3)^\n\nCheck out coverage by the [New York Times](https://www.nytimes.com/interactive/2020/08/24/climate/racism-redlining-cities-global-warming.html).\n\nA recent study found that redlining has not only affected the environments communities are exposed to, it has also shaped our observations of biodiversity.^[4](https://eds-223-geospatial.github.io/assignments/HW2.html#fn4)^ Community or citizen science, whereby individuals share observations of species, is generating an enormous volume of data. Ellis-Soto and co-authors found that redlined neighborhoods remain the most undersampled areas across 195 US cities. This gap is highly concerning, because conservation decisions are made based on these data.\n\nCheck out coverage by [EOS](https://eos.org/articles/bird-biodiversity-reports-reflect-cities-redlined-past?utm_source=EosBuzz&mkt_tok=OTg3LUlHVC01NzIAAAGOx3ckQPpeDY3QyFKdUnBSYqILj3qLrgb_Q2lasphwcF90xEzMgjZFUo3NHsw3caXDcZe6I8D8qdVsSRr3wzhb6LKAQRgNo8ffhjieEbDwMw).\n\n## About the Data\n\n### **EJScreen**\n\n**Data file:** `ejscreen/EJSCREEN_2023_BG_StatePct_with_AS_CNMI_GU_VI.gdb`\n\nWe will be working with data from the United States Environmental Protection Agency's EJScreen: Environmental Justice Screening and Mapping Tool.\n\nAccording to the [US EPA website](https://www.epa.gov/ejscreen/purposes-and-uses-ejscreen):\n\n> This screening tool and data may be of interest to community residents or other stakeholders as they search for environmental or demographic information. It can also support a wide range of research and policy goals. The public has used EJScreen in many different locations and in many different ways.\n>\n> EPA is sharing EJScreen with the public:\\\n> - to be more transparent about how we consider environmental justice in our work,\\\n> - to assist our stakeholders in making informed decisions about pursuing environmental justice and,\\\n> - to create a common starting point between the agency and the public when looking at issues related to environmental justice.\n\nEJScreen provides on environmental and demographic information for the US at the Census [tract](https://en.wikipedia.org/wiki/Census_tract) and [block group](https://en.wikipedia.org/wiki/Census_block_group) levels. We will be working with data at the block group level that has been downloaded from the [EPA site](https://www.epa.gov/ejscreen/download-ejscreen-data). To understand the associated data columns, we will need to explore the following in the `data` folder:\n\n-   Technical documentation: `ejscreen-tech-doc-version-2-2.pdf`\n\n-   Column descriptions: `EJSCREEN_2023_BG_Columns.xlsx`\n\nYou should also explore the [limitations and caveats](https://www.epa.gov/ejscreen/limitations-and-caveats-using-ejscreen) of the data.\n\n### **HOLC Redlining**\n\n**Data file:** `mapping-inequality/mapping-inequality-los-angeles.json`\n\nA team of researchers, led by the [Digital Scholarship Lab](https://dsl.richmond.edu/) at the University of Richmond have digitized maps and information from the HOLC as part of the [Mapping Inequality](https://dsl.richmond.edu/panorama/redlining/#loc=5/39.1/-94.58) project.\n\nWe will be working with maps of HOLC grade designations for Los Angeles. Information on the data can be found [here](https://dsl.richmond.edu/panorama/redlining/#loc=5/39.1/-94.58&text=downloads).^[5](https://eds-223-geospatial.github.io/assignments/HW2.html#fn5)^\n\n### **Biodiversity observations**\n\n**Data file:** `gbif-birds-LA.shp`\n\nThe [Global Biodiversity Information Facility](https://eds-223-geospatial.github.io/assignments/gbif.org) is the largest aggregator of biodiversity observations in the world. Observations typically include a location and date that a species was observed.\n\nWe will be working observations of birds from 2021 onward.\n\n## Workflow\n\n### 1. Exploring the EJscreen Dataset and Understanding Key Characteristics of the Census Groups\n\nLet's start by setting up our workflow. You'll need to load the relevant packages for this project\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load relevant packages\nlibrary(tidyverse)\nlibrary(sf)\nlibrary(tmap)\nlibrary(tmaptools)\nlibrary(leaflet)\nlibrary(gt)\n```\n:::\n\n\nYou'll also need to read in the data from the EJScreen Database\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Use st_read() to read in the data\nejscreen <- st_read(\"data/ejscreen/EJSCREEN_2023_BG_StatePct_with_AS_CNMI_GU_VI.gdb/\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nReading layer `EJSCREEN_StatePctiles_with_AS_CNMI_GU_VI' from data source \n  `/Users/heatherchilders/Documents/MEDS/Personal Website/hmchilders.github.io/Geospatial_Blogs/2023-11-10/data/ejscreen/EJSCREEN_2023_BG_StatePct_with_AS_CNMI_GU_VI.gdb' \n  using driver `OpenFileGDB'\nSimple feature collection with 243021 features and 223 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -19951910 ymin: -1617130 xmax: 16259830 ymax: 11554350\nProjected CRS: WGS 84 / Pseudo-Mercator\n```\n:::\n:::\n\n\nLet's look at how low income groups are impacted by waste water discharge. We can do this by making a map of Los Angeles County, showing the proportion of low income homes in each census group. We can then indicate which areas experience above the 95th percentile of national values for waste water discharge by adding a centroid.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Filter the EJ Screen data to just the Los Angeles County and remove and missing data\ncropped_LA <- ejscreen %>%\n  filter(CNTY_NAME %in% c(\"Los Angeles County\")) %>% \n  drop_na()\n#Now create a subgroup of just the census blocks in LA that are above the 95% for wastewater discharge\nLA_95 <- cropped_LA %>% \n  filter(P_PWDIS > 95)\n\n#Create the map of LA County with Income and Wastewater Variables \ntm_shape(cropped_LA)+ #Make a map of LA County\n  tm_basemap()+\n  tm_graticules()+ #add gridlines\n    tm_scale_bar(position = c(\"left\", \"bottom\"))+ #Add a scalebar\n  tm_fill(fill = 'LOWINCPCT', #Fill each area based on the proportion of low income families\n          fill.scale = tm_scale(breaks = c(0,.10,.20,.30,.40,.50,.60,.70,.80,.90, 1)), #Set the breaks\n          fill.legend = tm_legend(title = 'Proportion of Low Income Individuals'))+ #Add a legend title\n  tm_shape(LA_95)+ #Add the wastewater data\n  tm_symbols(size = 0.1, #Set the size of the centroids\n             col = \"red\") #Set the color of the centriods\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\nWe can see what percentage of census block groups have less than 5% of the population considered low income.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Create a new dataframe that filters the LA County dataset to just the census groups that have less than 5% of the population considered low income\ntop_5_income <- cropped_LA %>% \n  filter(LOWINCPCT < 0.05)\n\n# Calculate the percentage \npct_top <- (length(top_5_income$LOWINCPCT)/length(cropped_LA$LOWINCPCT))*100\n#Print the percentage\npct_top\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 5.490134\n```\n:::\n:::\n\n\nFrom the workflow above, we can see that 5.49% of the census block groups have less that 5% of the population considered low income.\n\nUsing a similar workflow, we can find the percent of census block groups that are above the 80th percentile for Particulate Matter 2.5 AND above the 80th percentile for Superfund proximity\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Create a dataframe of the census block groups that are above the 80th percentile for Particulate Matter 2.5 AND above the 80th percentile for Superfund proximity\npctl_80 <- cropped_LA %>% \n  filter(P_PM25 > 80 & P_PNPL > 80)\n\n#Calculate the percentage\npct_above_80 <- (nrow(pctl_80)/nrow(cropped_LA))*100\n#print the percentage\npct_above_80\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 17.87078\n```\n:::\n:::\n\n\nFrom the workflow above, we can see that 17.87% of census block groups are above the 80th percentile for both PM 2.5 and Superfund proximity.\n\n### 2. Analyzing historical redlining in Los Angeles and its legacy on present-day environmental justice\n\nStart by importing the redlining information for Los Angeles.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Read in the data\nLA_redlining <- st_read(\"data/mapping-inequality/mapping-inequality-los-angeles.json\") %>%\n  st_make_valid()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nReading layer `mapping-inequality-los-angeles' from data source \n  `/Users/heatherchilders/Documents/MEDS/Personal Website/hmchilders.github.io/Geospatial_Blogs/2023-11-10/data/mapping-inequality/mapping-inequality-los-angeles.json' \n  using driver `GeoJSON'\nSimple feature collection with 417 features and 14 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -118.6104 ymin: 33.70563 xmax: -117.7028 ymax: 34.30388\nGeodetic CRS:  WGS 84\n```\n:::\n:::\n\n\nNow let visualize the relining information by making a map of historical redlining boundaries, colored by HOLC grade\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  tm_shape(LA_redlining)+\n    tm_basemap()+\n  tm_graticules()+\n    tm_scale_bar()+\n  tm_polygons('grade',\n          palette = c(\"chartreuse\", \"darkturquoise\", \"gold1\", \"firebrick2\"))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n**Let's quickly compare the redlinging data to the LA County data we looked at before by finding the number of census block groups that fall within areas with HOLC grades hint: make sure the CRS match**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Check the crs matching using the commented out code as shown below:\n#st_scr(data 1) == st_crs(data 2)\n\n#Make the datasets have the same coordinate refernce system\nLA_transform <- st_transform(LA_redlining, crs = 3857)\n#Join the two maps by figuring out which census blocks from the redlining data intersect with the LA County data\njoined_mapping <- st_intersection(LA_transform, cropped_LA)\n\n#Count and print the number of intersecting census blocks; we added unique to the are id to ensure census blocks weren't counted more than once\nlength(unique(joined_mapping$ID))\n```\n:::\n\n\nThe number of census block groups that fall within HOLC grade areas is 3818.\n\nAdditionally, we can summarize current conditions based on EJScreen data within historical redlining categories using the mean of the following variables:\\\n-% low income.\\\n- percentile for particulate Matter 2.5.\\\n- percentile for low life expectancy.\\\n- percentile for air toxics cancer risk\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Make the datasets have the same coordinate refernce system\nLA_transform <- st_transform(LA_redlining, crs = 3857)\n#Join the two maps by figuring out which census blocks from the redlining data intersect with the LA County data\njoined_mapping <- st_intersection(LA_transform, cropped_LA)\n\n#Create a table of summary statistics\nSumm_stats <- joined_mapping %>%\n  st_drop_geometry() %>% #Remove the geospatial component since we just want a table, not a map\n  group_by(grade) %>% #Group the data by holc grade so we can see stats by grade\n  summarize(avg_pct_LowIncome = mean(LOWINCPCT, na.rm = TRUE), #Calculate the mean low income%\n            avg_pctl_PM25 = mean(P_PM25, na.rm = TRUE), #Calculate the mean PM2.5 percentile\n            avg_pctl_LifeExpt = mean(P_LIFEEXPPCT, na.rm = TRUE), #Calculate the low life expect. percentile\n            avg_pctl_Cancer = mean(P_CANCER, na.rm = TRUE)) %>% #Calculate the cancer risk percentile\n  gt() #Create a nice table using gt\n\n#Print the table\nSumm_stats\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"oqbhkuwbsi\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#oqbhkuwbsi table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#oqbhkuwbsi thead, #oqbhkuwbsi tbody, #oqbhkuwbsi tfoot, #oqbhkuwbsi tr, #oqbhkuwbsi td, #oqbhkuwbsi th {\n  border-style: none;\n}\n\n#oqbhkuwbsi p {\n  margin: 0;\n  padding: 0;\n}\n\n#oqbhkuwbsi .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#oqbhkuwbsi .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#oqbhkuwbsi .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#oqbhkuwbsi .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#oqbhkuwbsi .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#oqbhkuwbsi .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#oqbhkuwbsi .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#oqbhkuwbsi .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#oqbhkuwbsi .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#oqbhkuwbsi .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#oqbhkuwbsi .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#oqbhkuwbsi .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#oqbhkuwbsi .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#oqbhkuwbsi .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#oqbhkuwbsi .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#oqbhkuwbsi .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#oqbhkuwbsi .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#oqbhkuwbsi .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#oqbhkuwbsi .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#oqbhkuwbsi .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#oqbhkuwbsi .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#oqbhkuwbsi .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#oqbhkuwbsi .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#oqbhkuwbsi .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#oqbhkuwbsi .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#oqbhkuwbsi .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#oqbhkuwbsi .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#oqbhkuwbsi .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#oqbhkuwbsi .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#oqbhkuwbsi .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#oqbhkuwbsi .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#oqbhkuwbsi .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#oqbhkuwbsi .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#oqbhkuwbsi .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#oqbhkuwbsi .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#oqbhkuwbsi .gt_left {\n  text-align: left;\n}\n\n#oqbhkuwbsi .gt_center {\n  text-align: center;\n}\n\n#oqbhkuwbsi .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#oqbhkuwbsi .gt_font_normal {\n  font-weight: normal;\n}\n\n#oqbhkuwbsi .gt_font_bold {\n  font-weight: bold;\n}\n\n#oqbhkuwbsi .gt_font_italic {\n  font-style: italic;\n}\n\n#oqbhkuwbsi .gt_super {\n  font-size: 65%;\n}\n\n#oqbhkuwbsi .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#oqbhkuwbsi .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#oqbhkuwbsi .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#oqbhkuwbsi .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#oqbhkuwbsi .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#oqbhkuwbsi .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#oqbhkuwbsi .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#oqbhkuwbsi .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#oqbhkuwbsi div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"grade\">grade</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"avg_pct_LowIncome\">avg_pct_LowIncome</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"avg_pctl_PM25\">avg_pctl_PM25</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"avg_pctl_LifeExpt\">avg_pctl_LifeExpt</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"avg_pctl_Cancer\">avg_pctl_Cancer</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"grade\" class=\"gt_row gt_left\">A</td>\n<td headers=\"avg_pct_LowIncome\" class=\"gt_row gt_right\">0.1506682</td>\n<td headers=\"avg_pctl_PM25\" class=\"gt_row gt_right\">72.22917</td>\n<td headers=\"avg_pctl_LifeExpt\" class=\"gt_row gt_right\">23.71991</td>\n<td headers=\"avg_pctl_Cancer\" class=\"gt_row gt_right\">44.08102</td></tr>\n    <tr><td headers=\"grade\" class=\"gt_row gt_left\">B</td>\n<td headers=\"avg_pct_LowIncome\" class=\"gt_row gt_right\">0.2412924</td>\n<td headers=\"avg_pctl_PM25\" class=\"gt_row gt_right\">76.33249</td>\n<td headers=\"avg_pctl_LifeExpt\" class=\"gt_row gt_right\">37.42025</td>\n<td headers=\"avg_pctl_Cancer\" class=\"gt_row gt_right\">47.97384</td></tr>\n    <tr><td headers=\"grade\" class=\"gt_row gt_left\">C</td>\n<td headers=\"avg_pct_LowIncome\" class=\"gt_row gt_right\">0.3362853</td>\n<td headers=\"avg_pctl_PM25\" class=\"gt_row gt_right\">78.83678</td>\n<td headers=\"avg_pctl_LifeExpt\" class=\"gt_row gt_right\">47.88017</td>\n<td headers=\"avg_pctl_Cancer\" class=\"gt_row gt_right\">54.63602</td></tr>\n    <tr><td headers=\"grade\" class=\"gt_row gt_left\">D</td>\n<td headers=\"avg_pct_LowIncome\" class=\"gt_row gt_right\">0.3902902</td>\n<td headers=\"avg_pctl_PM25\" class=\"gt_row gt_right\">80.25829</td>\n<td headers=\"avg_pctl_LifeExpt\" class=\"gt_row gt_right\">53.03624</td>\n<td headers=\"avg_pctl_Cancer\" class=\"gt_row gt_right\">56.43022</td></tr>\n    <tr><td headers=\"grade\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"avg_pct_LowIncome\" class=\"gt_row gt_right\">0.3542969</td>\n<td headers=\"avg_pctl_PM25\" class=\"gt_row gt_right\">76.29197</td>\n<td headers=\"avg_pctl_LifeExpt\" class=\"gt_row gt_right\">50.12409</td>\n<td headers=\"avg_pctl_Cancer\" class=\"gt_row gt_right\">41.45255</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\nBreaking the percentiles down into each HOLC grade shows some troubling statistics about the quality of life differences between grades. For the percent of the population considered low income, the percent in HOLC grade A communities is only 15%. For D grade communities in the same category, the percentage jumps to almost 40%. This trend is true for all of the categories explored in this table including the average percentile for PM2.5 concentration, the average percentile for low life expectancy, and average percentile for cancer risk. Average PM2.5 concentration and average percentile for cancer risk have the smallest differences between A and D groups. This data implies that policy decisions are affecting the \"safety ratings\" for the HOLC grades, and disadvantaged groups are being targeted.\n\n### Investigate the legacy of redlining in biodiversity observations\n\nFor bird observations from 2022 that fall within neighborhoods with HOLC grades, we can find the percent of observations within each redlining categories and plot results. Remember to always make sure that the bird observations have the same CRS as redlining data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Read in the data\nbird_data <- st_read(\"data/gbif-birds-LA/\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nReading layer `gbif-birds-LA' from data source \n  `/Users/heatherchilders/Documents/MEDS/Personal Website/hmchilders.github.io/Geospatial_Blogs/2023-11-10/data/gbif-birds-LA' \n  using driver `ESRI Shapefile'\nSimple feature collection with 1288865 features and 1 field\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: -118.6099 ymin: 33.70563 xmax: -117.7028 ymax: 34.30385\nGeodetic CRS:  WGS 84\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Filter just to the observations for 2022\nbirds <- bird_data %>% \n  filter(year == \"2022\")\n#Make sure the CRS match\nst_crs(birds) == st_crs(LA_redlining)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] TRUE\n```\n:::\n\n```{.r .cell-code}\n#Join the data\njoined_birds <- st_join(LA_redlining,birds)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Calculate the percentage of observations from each HOLC Grade\ngrade_pct <- joined_birds %>% \n  group_by(grade) %>% \n  summarize(obsv_pct = ((n()/nrow(joined_birds))*100))\n\n#Plot the data\nggplot(grade_pct, aes(x = grade, y = obsv_pct))+\n  geom_col(fill = c(\"chartreuse\", \"darkturquoise\", \"gold1\", \"firebrick2\",\"grey\"))+\n  labs(x = \"HOLC Grades\",\n       y = \"Precent of observation\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\nThese results are not what I would've initially expected. I would've expected the majority of the observations to be in A and B grades because the areas are better protected which would encourage bird populations, and the people living in these areas are more affluent and are more likely to spend time bird watching. One reason there might be a higher percentage of sightings in the C and D grade communities is because people living in these areas are more likely to care about the quality of their environment because they are experiencing the effects of increased PM and exposure to toxins.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#additional graph\nid_pct <-joined_birds %>% \n  group_by(grade) %>% \n  summarize(obs_pct = ((n()/nrow(joined_birds))*100))\n\ntm_shape(LA_redlining)+\n  tm_fill('grade', \n          palette = c(\"chartreuse\", \"darkturquoise\", \"gold1\", \"firebrick2\", \"grey\" ))+\n  tm_shape(id_pct)+\n  tm_symbols('obs_pct')\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}